import type { Tool } from "../backend";

export const FALLBACK_TOOLS: Tool[] = [
  // Organize
  {
    id: "1",
    name: "Merge PDF",
    slug: "merge-pdf",
    category: "Organize",
    tier: "free",
    description: "Combine multiple PDF files into one seamless document.",
    iconName: "GitMerge",
  },
  {
    id: "2",
    name: "Split PDF",
    slug: "split-pdf",
    category: "Organize",
    tier: "free",
    description: "Split a PDF into multiple files or extract specific pages.",
    iconName: "Scissors",
  },
  {
    id: "3",
    name: "Rotate PDF",
    slug: "rotate-pdf",
    category: "Organize",
    tier: "free",
    description:
      "Rotate one or all pages of your PDF to the correct orientation.",
    iconName: "RotateCcw",
  },
  {
    id: "4",
    name: "Reorder Pages",
    slug: "reorder-pdf",
    category: "Organize",
    tier: "free",
    description: "Drag and drop to rearrange pages in any order you need.",
    iconName: "LayoutGrid",
  },
  // Convert
  {
    id: "5",
    name: "PDF to Word",
    slug: "pdf-to-word",
    category: "Convert",
    tier: "free",
    description: "Convert PDF documents to editable Word .docx files.",
    iconName: "FileText",
  },
  {
    id: "6",
    name: "PDF to Excel",
    slug: "pdf-to-excel",
    category: "Convert",
    tier: "free",
    description: "Extract tables and data from PDFs into Excel spreadsheets.",
    iconName: "Table2",
  },
  {
    id: "7",
    name: "PDF to PowerPoint",
    slug: "pdf-to-ppt",
    category: "Convert",
    tier: "free",
    description: "Transform PDF slides into editable PowerPoint presentations.",
    iconName: "PresentationIcon",
  },
  {
    id: "8",
    name: "PDF to JPG",
    slug: "pdf-to-jpg",
    category: "Convert",
    tier: "free",
    description: "Convert each PDF page to a high-quality JPG image.",
    iconName: "Image",
  },
  {
    id: "9",
    name: "Word to PDF",
    slug: "word-to-pdf",
    category: "Convert",
    tier: "free",
    description: "Convert Word documents to PDF with perfect formatting.",
    iconName: "FileType",
  },
  {
    id: "10",
    name: "Excel to PDF",
    slug: "excel-to-pdf",
    category: "Convert",
    tier: "free",
    description: "Turn Excel spreadsheets into polished PDF documents.",
    iconName: "FileSpreadsheet",
  },
  {
    id: "11",
    name: "PowerPoint to PDF",
    slug: "ppt-to-pdf",
    category: "Convert",
    tier: "free",
    description: "Convert PowerPoint slides to PDF for easy sharing.",
    iconName: "Presentation",
  },
  {
    id: "12",
    name: "JPG to PDF",
    slug: "jpg-to-pdf",
    category: "Convert",
    tier: "free",
    description: "Combine one or more images into a single PDF file.",
    iconName: "Images",
  },
  // Optimize
  {
    id: "13",
    name: "Compress PDF",
    slug: "compress-pdf",
    category: "Optimize",
    tier: "free",
    description: "Reduce PDF file size without sacrificing quality.",
    iconName: "Minimize2",
  },
  {
    id: "14",
    name: "PDF to Grayscale",
    slug: "grayscale-pdf",
    category: "Optimize",
    tier: "free",
    description: "Convert a color PDF to black and white for printing.",
    iconName: "Contrast",
  },
  {
    id: "15",
    name: "Repair PDF",
    slug: "repair-pdf",
    category: "Optimize",
    tier: "free",
    description: "Attempt to fix and recover corrupted or damaged PDF files.",
    iconName: "Wrench",
  },
  {
    id: "16",
    name: "Flatten PDF",
    slug: "flatten-pdf",
    category: "Optimize",
    tier: "free",
    description: "Flatten form fields and annotations into static content.",
    iconName: "Layers",
  },
  // Security
  {
    id: "17",
    name: "Protect PDF",
    slug: "protect-pdf",
    category: "Security",
    tier: "free",
    description: "Add password protection and permissions to your PDF.",
    iconName: "Lock",
  },
  {
    id: "18",
    name: "Unlock PDF",
    slug: "unlock-pdf",
    category: "Security",
    tier: "free",
    description: "Remove password protection from a PDF you own.",
    iconName: "Unlock",
  },
  // Edit
  {
    id: "19",
    name: "Add Watermark",
    slug: "watermark-pdf",
    category: "Edit",
    tier: "free",
    description: "Stamp text or image watermarks onto PDF pages.",
    iconName: "Stamp",
  },
  {
    id: "20",
    name: "Remove Watermark",
    slug: "remove-watermark",
    category: "Edit",
    tier: "free",
    description: "Detect and remove watermarks from PDF documents.",
    iconName: "Eraser",
  },
  {
    id: "21",
    name: "Add Page Numbers",
    slug: "page-numbers",
    category: "Edit",
    tier: "free",
    description: "Insert customizable page numbers at any position.",
    iconName: "Hash",
  },
  {
    id: "22",
    name: "Crop PDF",
    slug: "crop-pdf",
    category: "Edit",
    tier: "free",
    description: "Crop and resize the visible area of PDF pages.",
    iconName: "Crop",
  },
  {
    id: "23",
    name: "Edit Metadata",
    slug: "edit-metadata",
    category: "Edit",
    tier: "free",
    description: "Update title, author, subject, and keyword metadata.",
    iconName: "Tags",
  },
  // Advanced (Premium)
  {
    id: "24",
    name: "Sign PDF",
    slug: "sign-pdf",
    category: "Advanced",
    tier: "premium",
    description: "Draw, type, or upload your signature to any PDF document.",
    iconName: "PenTool",
  },
  {
    id: "25",
    name: "Annotate PDF",
    slug: "annotate-pdf",
    category: "Advanced",
    tier: "premium",
    description: "Add highlights, comments, shapes, and text annotations.",
    iconName: "MessageSquare",
  },
  {
    id: "26",
    name: "Compare PDFs",
    slug: "compare-pdf",
    category: "Advanced",
    tier: "premium",
    description: "View two PDFs side-by-side and highlight differences.",
    iconName: "GitCompare",
  },
];

export const CATEGORIES = [
  "All",
  "Organize",
  "Convert",
  "Optimize",
  "Security",
  "Edit",
  "Advanced",
] as const;
export type Category = (typeof CATEGORIES)[number];
