/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Tool = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'tier' : IDL.Text,
  'description' : IDL.Text,
  'iconName' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllTools' : IDL.Func([], [IDL.Vec(Tool)], ['query']),
  'getToolBySlug' : IDL.Func([IDL.Text], [Tool], ['query']),
  'getToolsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Tool)], ['query']),
  'getToolsByTier' : IDL.Func([IDL.Text], [IDL.Vec(Tool)], ['query']),
  'getUsageStats' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Tool = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'tier' : IDL.Text,
    'description' : IDL.Text,
    'iconName' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllTools' : IDL.Func([], [IDL.Vec(Tool)], ['query']),
    'getToolBySlug' : IDL.Func([IDL.Text], [Tool], ['query']),
    'getToolsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Tool)], ['query']),
    'getToolsByTier' : IDL.Func([IDL.Text], [IDL.Vec(Tool)], ['query']),
    'getUsageStats' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };